language: python

python:
  - '3.6'

service:
  - postgresql

install:
- pip install -r requirements.txt

before_script:
  - export APP_SETTINGS="flask_users.config.TestingConfig"
  - export DATABASE_TEST_URL=postgresql://postgres:@localhost/users_test
  - psql -c "CREATE DATABASE users_test;" -U postgresql
  - python manage.py recreate_db

script:
  - python manage.py test
  