version: "2.1"

services:
  users-db:
    container_name: users-db
    build: ./flask_users/db
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password1234
    healthcheck:
      test: exit 0

  users-service:
    container_name: users-service
    build: .
    ports:
      - "5000"
    environment:
      - APP_SETTINGS=flask_users.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:password1234@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:password1234@users-db:5432/users_test
      - SECRET_KEY='\xda\xf2;\x08\xfeRy\xb2W\xc4\xcf\xbc\x96\x82\x8eD\xe6\xde\xa3\x90_5\xcf\xed'
    depends_on:
      users-db:
        condition: service_healthy
    links:
      - users-db
    command: gunicorn -b 0.0.0.0:5000 manage:app

  web-service:
    container_name: web-service
    build:
      context: ./flask_client
      args:
        REACT_APP_USERS_SERVICE_URL: ${REACT_APP_USERS_SERVICE_URL}
    environment:
      - NODE_ENV=production
    ports:
      - "8080:8080"
    depends_on:
      users-service:
        condition: service_started
    links:
      - users-service

  nginx:
    container_name: nginx
    build: ./flask_users/nginx/
    restart: always
    ports:
      - 80:80
    depends_on:
      users-service:
        condition: service_started
      web-service:
        condition: service_started
    links:
      - users-service
      - web-service
