version: '2.1'

services:
  users-db:
    container_name: users-db
    build: ./flask_users/db
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password1234
    healthcheck:
      test: exit 0

  users-service:
    container_name: users-service
    build: .
    ports:
      - '5000' 
    environment:
      - APP_SETTINGS=flask_users.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:password1234@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:password1234@users-db:5432/users_test
    depends_on:
      users-db:
        condition: service_healthy
    links:
      - users-db
    command: gunicorn -b 0.0.0.0:5000 manage:app
    
  nginx:
    container_name: nginx
    build: ./flask_users/nginx/
    restart: always
    ports:
      - 80:80
    depends_on:
      users-service:
        condition: service_started
    links:
      - users-service

